config/routes.rb
Rails.application.routes.draw do
  get 'memes/index'

  resources :memes

  root 'welcome#index'
    #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meme.rb
class Meme < ApplicationRecord
  mount_uploader :picture_url, ImageUploader
  validates :title, presence: true, length: {minimum: 2}
  validates :picture_url, file_size: { less_than: 2.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only: [:show, :edit, :update, :destroy]

  def index
    @memes = Meme.order('created_at DESC')
  end

  def show
  end

  def new
    @meme = Meme.new
  end

  def create
    @meme = Meme.new(meme_params)
    if @meme.save
      redirect_to memes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @meme.update_attributes(meme_params)
      redirect_to meme_path(@meme)
    else
      render :edit
    end
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy

    redirect_to memes_path
  end

  def default_url
    "/assets/empty.png"
  end

  private

  def meme_params
    params.require(:meme).permit(:stack_id, :mark, :title, :picture_url, :picture_url_cache, :remote_picture_url_url)
  end

  def set_meme
    @meme = Meme.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemeEvaluator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memes/_form.html.erb
<%= form_for meme do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>


  <div>
    <%= f.label :image %>
    <%= f.file_field :picture_url %>
    <%= f.hidden_field :picture_url_cache %>
  </div>

  <div>
    <%= f.text_field :remote_picture_url_url %>
    <small>Enter URL to an image</small>
  </div>
  <% if meme.picture_url? %>
    <%= image_tag meme.picture_url.small_thumb.url %>
  <% end %>
  <%= f.submit %>




  <%= render 'shared/errors', object: meme %>
<% end %>

app/views/memes/_meme.html.erb
<h2><%= link_to meme.title, meme_path(meme) %></h2>



<p><%= link_to 'Edit', edit_meme_path(meme) %></p>
<hr>

app/views/memes/edit.html.erb
<h1>Edit meme</h1>

<%= render 'form', meme: @meme %>

app/views/memes/index.html.erb
<h1>Memes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Thumb</th>
    <th>Mark</th>
    <th></th>
  </tr>

  <% @memes.each do |meme| %>
    <tr>
      <td><%= meme.title %></td>
      <td><% if  meme.picture_url.present?  %>
          <%= image_tag meme.picture_url.small_thumb.url %>
        <% elsif meme.remote_picture_url_url.present?%>
            <%= image_tag meme.remote_picture_url.small_thumb.url %>
          <%else %>
              <%= image_tag "/public/empty.png", size: "30x30"  %>

        <%end %></td>
      <td><%= meme.mark %></td>
      <td><%= link_to 'Show', meme_path(meme) %></td>
      <td><%= link_to 'Delete', meme_path(meme),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Add meme', new_meme_path %>

app/views/memes/new.html.erb
<h1>Add meme</h1>

<%= render 'form', meme: @meme %>

app/views/memes/show.html.erb
<%= link_to 'All memes', memes_path %>
<h1><%= @meme.title %></h1>

<% if  @meme.picture_url.present?  %>
  <%= image_tag @meme.picture_url.url %>
<% elsif @meme.remote_picture_url_url.present?%>
  <%= image_tag @meme.remote_picture_url_url.url %>
<%end %>

<p><%= link_to 'Edit', edit_meme_path(@meme) %></p>



<%= form_for @meme do |f| %>
  <%= f.radio_button(:mark, "1") %>
  <%= f.label(:mark_1, "1") %>
  <%= f.radio_button(:mark, "2") %>
  <%= f.label(:mark_2, "2") %>
  <%= f.radio_button(:mark, "3") %>
  <%= f.label(:mark_3, "3") %>
  <%= f.radio_button(:mark, "4") %>
  <%= f.label(:mark_4, "4") %>
  <%= f.radio_button(:mark, "5") %>
  <%= f.label(:mark_5, "5") %>
  <%= f.radio_button(:mark, "6") %>
  <%= f.label(:mark_6, "6") %>
  <%= f.radio_button(:mark, "7") %>
  <%= f.label(:mark_7, "7") %>
  <%= f.radio_button(:mark, "8") %>
  <%= f.label(:mark_8, "8") %>
  <%= f.radio_button(:mark, "9") %>
  <%= f.label(:mark_9, "9") %>
  <%= f.radio_button(:mark, "10") %>
  <%= f.label(:mark_10, "10") %>
  <%= f.submit "Evaluate" %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h3>Some errors were found:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_form.html.erb
<%= f.label :pucture_url %>
<%= f.file_field :pucture_url %><br>
<%= f.hidden_field :pucture_url_cache %>
<% if meme.picture_url? %>
  <%= image_tag meme.picture_url.thumb.url %>
<% end %>

<%= f.text_field :remote_picture_url_url %>
<small>Enter URL to an image</small>